"""empty message

Revision ID: 1179e5409739
Revises: 2a66b8ba5e71
Create Date: 2014-06-30 18:11:23.505661

"""

# revision identifiers, used by Alembic.
revision = '1179e5409739'
down_revision = '2a66b8ba5e71'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
