"""empty message

Revision ID: 187d5ff5ed90
Revises: 494c9c963741
Create Date: 2014-06-30 10:49:01.626642

"""

# revision identifiers, used by Alembic.
revision = '187d5ff5ed90'
down_revision = '494c9c963741'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
