"""empty message

Revision ID: 194b9370bfde
Revises: 1eb58a0f3723
Create Date: 2014-06-29 20:57:34.959017

"""

# revision identifiers, used by Alembic.
revision = '194b9370bfde'
down_revision = '1eb58a0f3723'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
