"""empty message

Revision ID: 1d27fedaf81f
Revises: 490c433e3a5f
Create Date: 2014-06-29 20:43:16.402537

"""

# revision identifiers, used by Alembic.
revision = '1d27fedaf81f'
down_revision = '490c433e3a5f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('funding_round',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('homepage_url', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('founded_on_day', sa.Integer(), nullable=True),
    sa.Column('founded_on_month', sa.Integer(), nullable=True),
    sa.Column('founded_on_year', sa.Integer(), nullable=True),
    sa.Column('headquarters', sa.String(length=255), nullable=True),
    sa.Column('number_of_employees', sa.String(length=255), nullable=True),
    sa.Column('number_of_investments', sa.String(length=255), nullable=True),
    sa.Column('total_funding_usd', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('acquisition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('acquisition_day', sa.String(length=255), nullable=True),
    sa.Column('acquisition_month', sa.String(length=255), nullable=True),
    sa.Column('acquisition_year', sa.String(length=255), nullable=True),
    sa.Column('founded_on_day', sa.Integer(), nullable=True),
    sa.Column('founded_on_month', sa.Integer(), nullable=True),
    sa.Column('founded_on_year', sa.Integer(), nullable=True),
    sa.Column('headquarters', sa.String(length=255), nullable=True),
    sa.Column('number_of_employees', sa.String(length=255), nullable=True),
    sa.Column('homepage_url', sa.String(length=255), nullable=True),
    sa.Column('number_of_investments', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('total_funding_usd', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_title', sa.String(length=255), nullable=True),
    sa.Column('article_url', sa.String(length=255), nullable=True),
    sa.Column('article_date', sa.String(length=255), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('acquisition_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['acquisition_id'], ['acquisition.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competitor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('acquisition_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['acquisition_id'], ['acquisition.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('founder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('education', sa.String(length=255), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('acquisition_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['acquisition_id'], ['acquisition.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('acquisition_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['acquisition_id'], ['acquisition.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('acquisition_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['acquisition_id'], ['acquisition.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('website',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_title', sa.String(length=255), nullable=True),
    sa.Column('website_url', sa.String(length=255), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('acquisition_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['acquisition_id'], ['acquisition.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_categories',
    sa.Column('left', sa.Integer(), nullable=True),
    sa.Column('right', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['left'], ['company.id'], ),
    sa.ForeignKeyConstraint(['right'], ['category.id'], )
    )
    op.create_table('acquisition_categories',
    sa.Column('left', sa.Integer(), nullable=True),
    sa.Column('right', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['left'], ['acquisition.id'], ),
    sa.ForeignKeyConstraint(['right'], ['category.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('acquisition_categories')
    op.drop_table('company_categories')
    op.drop_table('website')
    op.drop_table('category')
    op.drop_table('investor')
    op.drop_table('founder')
    op.drop_table('competitor')
    op.drop_table('news')
    op.drop_table('acquisition')
    op.drop_table('product')
    op.drop_table('company')
    op.drop_table('funding_round')
    op.drop_table('investment')
    ### end Alembic commands ###
