"""empty message

Revision ID: 1e04b1072a22
Revises: 1179e5409739
Create Date: 2014-06-30 18:11:26.746180

"""

# revision identifiers, used by Alembic.
revision = '1e04b1072a22'
down_revision = '1179e5409739'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
