"""empty message

Revision ID: 1eb58a0f3723
Revises: 3f185d9192a
Create Date: 2014-06-29 20:57:21.702291

"""

# revision identifiers, used by Alembic.
revision = '1eb58a0f3723'
down_revision = '3f185d9192a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
