"""empty message

Revision ID: 1fa6015db494
Revises: 62e1d912811
Create Date: 2014-06-29 20:00:48.093278

"""

# revision identifiers, used by Alembic.
revision = '1fa6015db494'
down_revision = '62e1d912811'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
