"""empty message

Revision ID: 1fbe51f05503
Revises: 5d796ab1b7e
Create Date: 2014-06-30 14:36:54.983843

"""

# revision identifiers, used by Alembic.
revision = '1fbe51f05503'
down_revision = '5d796ab1b7e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
