"""empty message

Revision ID: 201febfd6bec
Revises: 462f4509877b
Create Date: 2014-07-01 11:30:08.315494

"""

# revision identifiers, used by Alembic.
revision = '201febfd6bec'
down_revision = '462f4509877b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
