"""empty message

Revision ID: 21e6ee9d8033
Revises: 1fbe51f05503
Create Date: 2014-06-30 15:54:17.682148

"""

# revision identifiers, used by Alembic.
revision = '21e6ee9d8033'
down_revision = '1fbe51f05503'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('acquisition_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'acquisition_id')
    ### end Alembic commands ###
