"""empty message

Revision ID: 25528410b073
Revises: 1fa6015db494
Create Date: 2014-06-29 20:08:36.908602

"""

# revision identifiers, used by Alembic.
revision = '25528410b073'
down_revision = '1fa6015db494'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
