"""empty message

Revision ID: 2a66b8ba5e71
Revises: 4363816edb7e
Create Date: 2014-06-30 17:56:44.038575

"""

# revision identifiers, used by Alembic.
revision = '2a66b8ba5e71'
down_revision = '4363816edb7e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
