"""empty message

Revision ID: 2cdd2b7bd288
Revises: 555894e9aa0
Create Date: 2014-06-29 20:19:17.397893

"""

# revision identifiers, used by Alembic.
revision = '2cdd2b7bd288'
down_revision = '555894e9aa0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
