"""empty message

Revision ID: 3396200b0172
Revises: 21e6ee9d8033
Create Date: 2014-06-30 16:02:48.397328

"""

# revision identifiers, used by Alembic.
revision = '3396200b0172'
down_revision = '21e6ee9d8033'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
