"""Added some more relationships

Revision ID: 35d20db68abc
Revises: None
Create Date: 2014-06-01 17:24:29.944398

"""

# revision identifiers, used by Alembic.
revision = '35d20db68abc'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('is_user_id', sa.Integer(), nullable=True))
    op.add_column('contact', sa.Column('job_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact', 'job_id')
    op.drop_column('contact', 'is_user_id')
    ### end Alembic commands ###
