"""empty message

Revision ID: 36637219240f
Revises: 25528410b073
Create Date: 2014-06-29 20:09:03.810868

"""

# revision identifiers, used by Alembic.
revision = '36637219240f'
down_revision = '25528410b073'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
