"""empty message

Revision ID: 3f185d9192a
Revises: 46f7c3d8270c
Create Date: 2014-06-29 20:57:17.480083

"""

# revision identifiers, used by Alembic.
revision = '3f185d9192a'
down_revision = '46f7c3d8270c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
