"""empty message

Revision ID: 42a7cc91702d
Revises: 49f493eb80fc
Create Date: 2014-06-23 15:26:50.900898

"""

# revision identifiers, used by Alembic.
revision = '42a7cc91702d'
down_revision = '49f493eb80fc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
