"""empty message

Revision ID: 4363816edb7e
Revises: e0af96ccc6f
Create Date: 2014-06-30 17:56:38.486310

"""

# revision identifiers, used by Alembic.
revision = '4363816edb7e'
down_revision = 'e0af96ccc6f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
