"""empty message

Revision ID: 462f4509877b
Revises: 1e04b1072a22
Create Date: 2014-07-01 11:30:05.593014

"""

# revision identifiers, used by Alembic.
revision = '462f4509877b'
down_revision = '1e04b1072a22'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
