"""empty message

Revision ID: 46f7c3d8270c
Revises: 4c9272f24c23
Create Date: 2014-06-29 20:52:52.752817

"""

# revision identifiers, used by Alembic.
revision = '46f7c3d8270c'
down_revision = '4c9272f24c23'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
