"""empty message

Revision ID: 490c433e3a5f
Revises: 5960b793a126
Create Date: 2014-06-29 20:33:00.617169

"""

# revision identifiers, used by Alembic.
revision = '490c433e3a5f'
down_revision = '5960b793a126'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
