"""empty message

Revision ID: 494c9c963741
Revises: 50bfdb6f580
Create Date: 2014-06-30 10:48:52.870825

"""

# revision identifiers, used by Alembic.
revision = '494c9c963741'
down_revision = '50bfdb6f580'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('acquisition', sa.Column('number_of_funding_rounds', sa.String(length=255), nullable=True))
    op.add_column('company', sa.Column('number_of_funding_rounds', sa.String(length=255), nullable=True))
    op.add_column('funding_round', sa.Column('acquisition_id', sa.Integer(), nullable=True))
    op.add_column('funding_round', sa.Column('company_id', sa.Integer(), nullable=True))
    op.add_column('funding_round', sa.Column('funding_amount', sa.String(length=255), nullable=True))
    op.add_column('funding_round', sa.Column('funding_type', sa.String(length=255), nullable=True))
    op.add_column('funding_round', sa.Column('investor_id', sa.Integer(), nullable=True))
    op.add_column('investor', sa.Column('investor_type', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('investor', 'investor_type')
    op.drop_column('funding_round', 'investor_id')
    op.drop_column('funding_round', 'funding_type')
    op.drop_column('funding_round', 'funding_amount')
    op.drop_column('funding_round', 'company_id')
    op.drop_column('funding_round', 'acquisition_id')
    op.drop_column('company', 'number_of_funding_rounds')
    op.drop_column('acquisition', 'number_of_funding_rounds')
    ### end Alembic commands ###
