"""empty message

Revision ID: 49f493eb80fc
Revises: None
Create Date: 2014-06-23 13:31:10.426786

"""

# revision identifiers, used by Alembic.
revision = '49f493eb80fc'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
