"""empty message

Revision ID: 4ad2f9e77998
Revises: 2cdd2b7bd288
Create Date: 2014-06-29 20:27:40.012885

"""

# revision identifiers, used by Alembic.
revision = '4ad2f9e77998'
down_revision = '2cdd2b7bd288'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
