"""empty message

Revision ID: 4c9272f24c23
Revises: 1d27fedaf81f
Create Date: 2014-06-29 20:47:30.677927

"""

# revision identifiers, used by Alembic.
revision = '4c9272f24c23'
down_revision = '1d27fedaf81f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
