"""empty message

Revision ID: 503ca819aa34
Revises: 194b9370bfde
Create Date: 2014-06-29 21:00:10.305280

"""

# revision identifiers, used by Alembic.
revision = '503ca819aa34'
down_revision = '194b9370bfde'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
