"""empty message

Revision ID: 508471754eef
Revises: 3396200b0172
Create Date: 2014-06-30 16:02:53.994153

"""

# revision identifiers, used by Alembic.
revision = '508471754eef'
down_revision = '3396200b0172'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
