"""empty message

Revision ID: 50bfdb6f580
Revises: 503ca819aa34
Create Date: 2014-06-29 21:09:05.970576

"""

# revision identifiers, used by Alembic.
revision = '50bfdb6f580'
down_revision = '503ca819aa34'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
