"""empty message

Revision ID: 555894e9aa0
Revises: 36637219240f
Create Date: 2014-06-29 20:10:37.924468

"""

# revision identifiers, used by Alembic.
revision = '555894e9aa0'
down_revision = '36637219240f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
