"""empty message

Revision ID: 5960b793a126
Revises: 4ad2f9e77998
Create Date: 2014-06-29 20:29:42.940989

"""

# revision identifiers, used by Alembic.
revision = '5960b793a126'
down_revision = '4ad2f9e77998'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
