"""empty message

Revision ID: 5d796ab1b7e
Revises: de49f48ddd7
Create Date: 2014-06-30 13:56:02.844369

"""

# revision identifiers, used by Alembic.
revision = '5d796ab1b7e'
down_revision = 'de49f48ddd7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
