"""empty message

Revision ID: 62e1d912811
Revises: 42a7cc91702d
Create Date: 2014-06-29 19:27:33.999600

"""

# revision identifiers, used by Alembic.
revision = '62e1d912811'
down_revision = '42a7cc91702d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
