"""empty message

Revision ID: de49f48ddd7
Revises: 187d5ff5ed90
Create Date: 2014-06-30 13:31:07.797291

"""

# revision identifiers, used by Alembic.
revision = 'de49f48ddd7'
down_revision = '187d5ff5ed90'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
