"""empty message

Revision ID: e0af96ccc6f
Revises: 508471754eef
Create Date: 2014-06-30 17:00:52.770602

"""

# revision identifiers, used by Alembic.
revision = 'e0af96ccc6f'
down_revision = '508471754eef'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
